services:
  telegram-bot:
    type: web
    env: python
    build:
      buildpacks:
        - python
    plan: free
    environment:
      BOT_TOKEN: "8537062188:AAHm1-8869H_MdIZLRITPh0YAInxpAKjqOA"
      API_KEY: "YOUR_AI_API_KEY_HERE"
      ADMIN_ID: "8087077168"
    webCommand: "python bot.py"
