services:
  - type: web
    name: homework-bot
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "8537062188:AAHm1-8869H_MdIZLRITPh0YAInxpAKjqOA"
      - key: API_KEY
        value: "free_temporary_key"
      - key: ADMIN_ID
        value: "8087077168"
