services:
  telegram-bot:
    type: web
    env: python
    build:
      buildpacks:
        - python
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: "8537062188:AAHm1-8869H_MdIZLRITPh0YAInxpAKjqOA"
      - key: API_KEY
        value: "1"
      - key: ADMIN_ID
        value: "8087077168"
    webCommand: "python bot.py"
